### ISSUE TITLE
Creating a module and export CLRObject error

### ISSUE THREAD

**Issue by thedacheng** [azurefx/DotNET.jl#18]
How can I export The `CLRObject`s? They seem to work fine in the same module. 
```
chengd@6ab5c36e4fce:/workspaces/jl$ julia --project=.
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.7.2 (2022-02-06)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

julia> using DotNET

julia> # Termstructure
       CLRtermstructure = T"System.Reflection.Assembly".LoadFrom(raw"/workspaces/fe/src/Termstructure/bin/Debug/net6.0/Termstructure.dll")
System.Reflection.RuntimeAssembly("Termstructure, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null")

julia> CLRBrent = T"Termstructure.Zbrent, Termstructure"
Termstructure.Zbrent

julia> CLRBrent.new()
Termstructure.Zbrent("Termstructure.Zbrent")

```
Once they are imported into another module, I see errors like:
```
chengd@6ab5c36e4fce:/workspaces/jl$ julia --project=.
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.7.2 (2022-02-06)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

julia> import EngTestWrapper

julia> EngTestWrapper.CLRtermstructure
Error showing value of type DotNET.CLRBridge.CLRObject:
ERROR: UndefRefError: access to undefined reference
Stacktrace:
  [1] unsafe_string(bstr::DotNET.BStr)
    @ DotNET ~/.julia/packages/DotNET/Rx490/src/typedef.jl:74
  [2] GetString
    @ ~/.julia/packages/DotNET/Rx490/src/CLRBridge.jl:167 [inlined]
  [3] string
    @ ~/.julia/packages/DotNET/Rx490/src/CLRBridge.jl:28 [inlined]
  [4] show(io::IOContext{Base.TTY}, x::DotNET.CLRBridge.CLRObject)
    @ DotNET ~/.julia/packages/DotNET/Rx490/src/reflection.jl:11
  [5] show(io::IOContext{Base.TTY}, #unused#::MIME{Symbol("text/plain")}, x::DotNET.CLRBridge.CLRObject)
    @ Base.Multimedia ./multimedia.jl:47
  [6] (::REPL.var"#43#44"{REPL.REPLDisplay{REPL.LineEditREPL}, MIME{Symbol("text/plain")}, Base.RefValue{Any}})(io::Any)
    @ REPL /julia-1.7.2/share/julia/stdlib/v1.7/REPL/src/REPL.jl:266
  [7] with_repl_linfo(f::Any, repl::REPL.LineEditREPL)
    @ REPL /julia-1.7.2/share/julia/stdlib/v1.7/REPL/src/REPL.jl:510
  [8] display(d::REPL.REPLDisplay, mime::MIME{Symbol("text/plain")}, x::Any)
    @ REPL /julia-1.7.2/share/julia/stdlib/v1.7/REPL/src/REPL.jl:259
  [9] display(d::REPL.REPLDisplay, x::Any)
    @ REPL /julia-1.7.2/share/julia/stdlib/v1.7/REPL/src/REPL.jl:271
 [10] display(x::Any)
    @ Base.Multimedia ./multimedia.jl:328
 [11] #invokelatest#2
    @ ./essentials.jl:716 [inlined]
 [12] invokelatest
    @ ./essentials.jl:714 [inlined]
 [13] print_response(errio::IO, response::Any, show_value::Bool, have_color::Bool, specialdisplay::Union{Nothing, AbstractDisplay})
    @ REPL /julia-1.7.2/share/julia/stdlib/v1.7/REPL/src/REPL.jl:293
 [14] (::REPL.var"#45#46"{REPL.LineEditREPL, Pair{Any, Bool}, Bool, Bool})(io::Any)
    @ REPL /julia-1.7.2/share/julia/stdlib/v1.7/REPL/src/REPL.jl:277
 [15] with_repl_linfo(f::Any, repl::REPL.LineEditREPL)
    @ REPL /julia-1.7.2/share/julia/stdlib/v1.7/REPL/src/REPL.jl:510
 [16] print_response(repl::REPL.AbstractREPL, response::Any, show_value::Bool, have_color::Bool)
    @ REPL /julia-1.7.2/share/julia/stdlib/v1.7/REPL/src/REPL.jl:275
 [17] (::REPL.var"#do_respond#66"{Bool, Bool, REPL.var"#77#87"{REPL.LineEditREPL, REPL.REPLHistoryProvider}, REPL.LineEditREPL, REPL.LineEdit.Prompt})(s::REPL.LineEdit.MIState, buf::Any, ok::Bool)
    @ REPL /julia-1.7.2/share/julia/stdlib/v1.7/REPL/src/REPL.jl:846
 [18] #invokelatest#2
    @ ./essentials.jl:716 [inlined]
 [19] invokelatest
    @ ./essentials.jl:714 [inlined]
 [20] run_interface(terminal::REPL.Terminals.TextTerminal, m::REPL.LineEdit.ModalInterface, s::REPL.LineEdit.MIState)
    @ REPL.LineEdit /julia-1.7.2/share/julia/stdlib/v1.7/REPL/src/LineEdit.jl:2493
 [21] run_frontend(repl::REPL.LineEditREPL, backend::REPL.REPLBackendRef)
    @ REPL /julia-1.7.2/share/julia/stdlib/v1.7/REPL/src/REPL.jl:1232
 [22] (::REPL.var"#49#54"{REPL.LineEditREPL, REPL.REPLBackendRef})()
    @ REPL ./task.jl:423
```
Thank you!

**Comment by azurefx** [comment]
`EngTestWrapper` is a module and is precompiled in a separate process before importing, so global variables hold pointers to CLR objects that no longer exist.

To fix this, I suggest you wrap your code in "getter" functions instead of using global variables. If you do need some initialization, then consider writing the code in an `__init__` function.

From [Julia documentation](https://docs.julialang.org/en/v1/manual/modules/#Module-initialization-and-precompilation):

> You may need to be aware of certain behaviors inherent in the creation of incremental shared libraries which may require care when writing your module. For example, external state is not preserved. To accommodate this, explicitly separate any initialization steps that must occur at runtime from steps that can occur at compile time. For this purpose, Julia allows you to define an `__init__()` function in your module that executes any initialization steps that must occur at runtime. This function will not be called during compilation (--output-*). Effectively, you can assume it will be run exactly once in the lifetime of the code. You may, of course, call it manually if necessary, but the default is to assume this function deals with computing state for the local machine, which does not need to be – or even should not be – captured in the compiled image. It will be called after the module is loaded into a process, including if it is being loaded into an incremental compile (--output-incremental=yes), but not if it is being loaded into a full-compilation process.
>
> In particular, if you define a function `__init__()` in a module, then Julia will call `__init__()` immediately after the module is loaded (e.g., by import, using, or require) at runtime for the first time (i.e., `__init__` is only called once, and only after all statements in the module have been executed). Because it is called after the module is fully imported, any submodules or other imported modules have their `__init__` functions called before the `__init__` of the enclosing module.

**Comment by thedacheng** [comment]
Thank you for the suggestion. I will study CLRBridge and try to get my code working in a similar way.

I tried `__precompile__(false)` which seemed to also solve the problem. Is this just a workaround, and `__init__()` is the right/preferred way to go? 

> If you know that a module is not safe to precompile (for example, for one of the reasons described below), you should put `__precompile__(false)` in the module file (typically placed at the top). This will cause `Base.compilecache` to throw an error, and will cause using / import to load it directly into the current process and skip the precompile and caching. This also thereby prevents the module from being imported by any other precompiled module.

**Comment by azurefx** [comment]
> `__init__()` is the right/preferred way to go?

Yes.

`PS /Users/azure/Desktop/MWE> gc ./Project.toml`
```toml
name = "MWE"
uuid = "c6b6bd35-9c8d-4662-8ec4-c63d7912f2e9"
authors = ["AzureFx <i@azurefx.name>"]
version = "0.1.0"

[deps]
DotNET = "5091b313-875f-492b-8fe1-0f0d7d725ad8"
```
`PS /Users/azure/Desktop/MWE> gc ./src/MWE.jl`
```julia
module MWE

using DotNET

# Occurs at compile time
const Console = Ref{CLRObject}()

function __init__()
    # Occurs at runtime
    Console[] = T"System.Console, mscorlib"
end

function hello()
    # This works as long as Console is valid
    Console[].WriteLine("Hello, World!");
end

function foo()
    # This also works because no global variables are involved (yay!)
    T"System.Tuple".Create[T"System.Int64"](42)
end

end # module
```
`PS /Users/azure/Desktop/MWE> julia --banner=no --project`
```
julia> using MWE
[ Info: Precompiling MWE [c6b6bd35-9c8d-4662-8ec4-c63d7912f2e9]

julia> MWE.hello()
Hello, World!
null

julia> MWE.foo().Item1
42
```

**Comment by thedacheng** [comment]
Thank you so much!
